services:
  Suez\Bundle\SmartCoachClientBundle\Client\JwtClient:
    arguments:
      - '%suez_smart_coach_client.jwt%'

  suez_smart_coach_client.jwt:
    alias: Suez\Bundle\SmartCoachClientBundle\Client\JwtClient
